apiVersion: apps/v1
kind: Deployment
metadata:
  name: emptydir-pod
  labels:
    app: emptydir-pod
#name space change 
  namespace: emptydir-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emptydir-pod
  template:
    metadata:
      labels:
        app: emptydir-pod
    spec:
      containers:
#     - image: 507115347197.dkr.ecr.ap-northeast-2.amazonaws.com/network-multitool
      - image: whchoi98/network-multitool
        name: emptydir-container
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
# Volume mounts point
        volumeMounts:
        - mountPath: /emptydir
          name: emptydir-volume
# volume
      volumes:
        - name: emptydir-volume
          emptyDir: {}
#add nodeSelector
      nodeSelector:
        nodegroup-type: "frontend-workloads"
        
