apiVersion: v1
kind: Service
metadata:
  name: istio-test01-svc
  namespace: istio-test01
spec:
  selector:
    app: istio-test01-app
  ports:
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 80