apiVersion: v1
kind: Service
metadata:
  name: alb-test-nlb
  namespace: alb-test-nlb
spec:
  selector:
    app: alb-test-nlb
  type: NodePort
  ports:
   -  protocol: TCP
      port: 8080
      targetPort: 80