apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  clusterIP: 172.17.10.100
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
